from src.publishers.base import BasePublisher
from playwright.sync_api import sync_playwright
from src.config import logger
from typing import Dict, Any
import os
import time

class RedditPublisher(BasePublisher):
    """
    Automates posting to Reddit using Browser Automation.
    Requires 'secrets/reddit_state.json' (generated by tools/auth_reddit.py).
    """
    
    def publish(self, content: Dict[str, Any]) -> str:
        state_path = "secrets/reddit_state.json"
        
        if not os.path.exists(state_path):
            logger.error("❌ No Reddit session found! Run tools/auth_reddit.py first.")
            return None

        with sync_playwright() as p:
            logger.info("🎭 Launching Headless Browser for Reddit...")
            
            # Keep visible so you can monitor
            browser = p.chromium.launch(headless=False) 
            context = browser.new_context(storage_state=state_path)
            page = context.new_page()

            # 1. Navigate
            subreddit = content.get("subreddit")
            if subreddit.startswith("u_"):
                clean_user = subreddit.replace("u_", "u/")
                submit_url = f"https://www.reddit.com/{clean_user}/submit"
            else:
                clean_sub = subreddit.replace("r/", "")
                submit_url = f"https://www.reddit.com/r/{clean_sub}/submit"
            
            logger.info(f"🔗 Navigating to {submit_url}...")
            page.goto(submit_url)
            page.wait_for_load_state("domcontentloaded")
            
            # 2. Fill Title
            logger.info("✍️ Typing Title...")
            title_box = page.locator("textarea[name='title'], textarea[placeholder='Title']").first
            title_box.click()
            title_box.fill(content["title"])
            time.sleep(1)

            # 3. Focus Body (The "Placeholder" Strategy)
            logger.info("🎯 Clicking Body Text Area...")
            
            # We try to click the generic placeholder text. 
            # This works for both the Rich Text Editor and Markdown Editor.
            try:
                # Look for 'Body text (optional)' OR 'Text (optional)'
                body_placeholder = page.locator("text='Body text (optional)'").or_(page.locator("text='Text (optional)'"))
                
                if body_placeholder.first.is_visible():
                    body_placeholder.first.click()
                else:
                    # Fallback: If text isn't found, try clicking the generic textbox div
                    logger.warning("⚠️ Placeholder text not found, trying generic textbox click...")
                    page.locator("div[role='textbox']").first.click()
                    
            except Exception as e:
                logger.error(f"Focus failed: {e}. Trying desperate Tab method...")
                page.keyboard.press("Tab")
                page.keyboard.press("Tab") # Press twice just in case

            time.sleep(0.5)

            # 4. Type Body
            logger.info("✍️ Typing Body...")
            page.keyboard.insert_text(content["body"])
            
            # 5. Click Post
            time.sleep(2)
            logger.info("👆 Clicking Post button...")
            
            post_button = page.get_by_role("button", name="Post", exact=True)
            
            if post_button.is_visible():
                post_button.click(force=True)
                logger.info("✅ Clicked Post!")
                
                # Wait for success
                try:
                    # Increased timeout to 20 seconds for safety
                    page.wait_for_load_state("networkidle", timeout=20000)
                    time.sleep(2)
                    final_url = page.url
                    logger.info(f"🎉 Published to: {final_url}")
                    return final_url
                except:
                    logger.warning("⚠️ Clicked post, but redirect timed out. Check manually.")
                    return "CHECK_MANUALLY"
            else:
                logger.error("❌ Post button not found or disabled.")
                return None